language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - museopkim0214@gmail.com

before_deploy:
  - zip -r songrequest-backend *
  - mkdir -p deploy
  - mv songrequest-backend.zip deploy/songrequest-backend.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: songrequest-backend-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      all_branches: true
